---
- name: copyplaybookAnsible
  hosts: all
  become: yes  
  tasks:
    - name: copyfile
      copy:
        src: /root/copyAnsible
        dest: /home/ubuntu 
    - name: packging_module
      apt:
        name: git
        state: latest
      when: ansible_os_family == 'Debian'      
